repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/pylint
    rev: v2.13.5
    hooks:
    -   id: pylint
        args: [
            "--disable=C0103",
            "--disable=C0114",
            "--disable=C0115",
            "--disable=C0116",
            "--disable=W0511",
            "--disable=W1514",
        ]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML]
-   repo: https://github.com/maltzj/google-style-precommit-hook
    rev: 95c2f5632710e095220e22cc1a4e1a1451abf75f
    hooks:
    -   id: google-style-java
