#!/usr/bin/env bash
set -euo pipefail

[ -d './demo/bricks/' ] || ( \
    echo './demo/bricks/ does not exist -- first run ./examples/bricks-demo' \
    && exit 1)
rm -f ./demo/shear-cycle/*
mkdir -p ./demo/shear-cycle
./scripts/mvn-compile
./bin/shear-cycle .5 .3 3 .02 2 .01 1 0 ./demo/bricks ./demo/shear-cycle TIFF
